service: task

frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs12.x


functions:
  hello:
    handler: handler.hello
    events:
      - http: ANY /{proxy+}
      - http: ANY /
    environment:
      PORT: 5000
      MONGODB_LOCAL_URL: mongodb://localhost:27017/tasks
      JWT_SECRET: mysecret123
      JWT_EXPIRE: 30s
      JWT_COOKIE_EXPIRE: 1
      USER_COOKIE: auth
